# Configuración del Blog - Estilo Terminal
title: "root@carlosmoreno:~$"
email: "periodistacarlosmoreno@gmail.com"
description: >-
  Bienvenido a mi terminal personal. Aquí documento ideas, proyectos y datos.
baseurl: "" 
url: "https://charlitos1.github.io" 

# Configuración del Tema
remote_theme: mre/jekyll-theme-terminal@master

# Plugins necesarios
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

# --- AJUSTES DE ESTILO TERMINAL ---
style: dark 
listen_for_clients_preferred_style: false 

# Personalización del Header
header_pages:
  - index.md
  - about.md

# Pie de página
footer: 'system.log: <a href="https://github.com/charlitos1">github</a>'
