# Configuración del Blog - Estilo Terminal
title: "root@carlosmoreno:~$"
email: "periodistacarlosmoreno@gmail.com"
description: >-
  Bienvenido a mi terminal personal. Aquí documento ideas, proyectos y datos.
baseurl: "" 
url: "https://charlitos1.github.io" 

# BORRAMOS remote_theme y el plugin jekyll-remote-theme
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# --- AJUSTES DE ESTILO TERMINAL ---
style: dark 
listen_for_clients_preferred_style: false 

header_pages:
  - index.md
  - archive.md
  - about.md

footer: 'system.log: <a href="https://github.com/charlitos1">github</a>'
